import * as THREE from 'three';
import controls from 'three-orbitcontrols';
import layout from 'ngraph.forcelayout3d';
import graph from 'ngraph.graph';
import stats from 'stats-js';
window.three = THREE;
window.ThreeControls = controls;
window.NgraphLayout = layout;
window.NgraphGraph = graph;
window.StatsJs = stats;
